CREATE TABLE IF NOT EXISTS worker (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH (NAME) >= 2),
    BIRTHDAY DATE CHECK (EXTRACT(YEAR FROM BIRTHDAY) >= 1900),
    LEVEL VARCHAR(10) NOT NULL CHECK (LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')),
    SALARY INTEGER CHECK (SALARY BETWEEN 100 AND 100000)
);

CREATE TABLE IF NOT EXISTS client (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH (NAME) >= 2)
);

CREATE SEQUENCE client_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS project (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CLIENT_ID INTEGER NOT NULL REFERENCES client(ID),
    START_DATE DATE,
    FINISH_DATE DATE
);

CREATE TABLE IF NOT EXISTS project_worker (
    PROJECT_ID INTEGER NOT NULL,
    FOREIGN KEY (PROJECT_ID) REFERENCES project(ID),
    WORKER_ID INTEGER NOT NULL,
    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID),
    PRIMARY KEY (PROJECT_ID, WORKER_ID)
);